In [1]:
import numpy as np

# Gaussian Elimination
def gaussian(A, b):
    n = len(b)
    
    # Forward elimination
    for i in range(n):
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        
        for j in range (i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
            
    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    
    return x

In [5]:
# Example from slides 11 through 16 of Week 6-1 lecture slides
A = [[2,3,-1],
     [4,-2,2],
     [-2,1,2]]
b = [5,6,-1]
solution = gaussian(A, b)
print(f"Solution: {solution}")

Solution: [1.5833333333333333, 0.8333333333333333, 0.6666666666666666]


In [3]:
# LU Decomposition
def lu_decomposition(A):
        n = len(A)
        L = np.eye(n) # Initialization of L as an identity matrix
        U = np.array(A, dtype=float) # Copy of A
        
        for i in range(n):
            for j in range (i+1, n):
                if U[i, i] ==0:
                    raise ValueError("Zero pivot encountered." + 
                                     "LU decomposition cannot proceed.")
                
                factor = U[j, i] / U[i, i] # Multiplier
                L [j, i] = factor # Store multiplier
                
                # Update rows of U
                for k in range (i, n):
                    U[j, k] -= factor * U[i, k]
        
        return L, U

In [7]:
# Example from slide 38 of Week 6-1 lecture slides
A = np.array([[2,3,1],
              [4,7,-1],
              [-2,1,2]])
L, U = lu_decomposition(A)
print("Matrix A:\n", A, "\n")
print("Lower Triangular Matrix L:\n", L, "\n")
print("Upper Triangular Matrix U:\n", U, "\n")

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]] 

Lower Triangular Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]] 

Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]] 

